- name: Install epel/remi repo
  package:
     name:
       - epel-release
       - http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
     state: present

- name: Install pwgen, unzip
  package:
     name: pwgen, unzip
     state: present

- name: Install python3-PyMySQL
  package:
     name: python3-PyMySQL
     state: present
  when: ansible_facts['distribution_major_version'] != "7"

- name: Install MySQL-python
  package:
     name: MySQL-python
     state: present
  when: ansible_facts['distribution_major_version'] != "8"
